server:
  port: 5000

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/interview-test
    username: interview
    password: app-interview
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  liquibase:
    enabled: false
    change-log: classpath:db/changelog/changelog-master.xml